name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [
          {name: "Ubuntu 22", os: "ubuntu-22.04", shell: "bash", compiler: "g++"},
          {name: "Ubuntu 24", os: "ubuntu-24.04", shell: "bash", compiler: "g++"},
          {name: "MacOS 13", os: "macos-13", shell: "bash", compiler: "g++-13"},
          {name: "MacOS 14 (M1)", os: "macos-14", shell: "bash", compiler: "g++-14"},
          {name: "Windows", os: "windows-2022", shell: "msys2", compiler: "g++"},
          {name: "Windows", os: "windows-2025", shell: "msys2", compiler: "g++"},
        ]
        projects: [
          {project: "hybrid_intracellular", name: "PhysiCell Boolean/Metabolic model", binary: "project", config: "config/PhysiCell_settings.xml", max_time: 20, output_folder: ""},
        ]
        
    name: Testing ${{ matrix.projects.name }} on ${{ matrix.os.name }}
        
    runs-on: ${{ matrix.os.os }}
    
    defaults:
      run:
        shell: ${{ matrix.os.shell }} {0}
        
    steps:
    - uses: actions/checkout@v4
    
    - if: matrix.os.name == 'Ubuntu 22' || matrix.os.name == 'Ubuntu 24'
      run: sudo apt-get update && sudo apt-get install -y liblapack-dev libopenblas-dev
      
    - if: matrix.os.name == 'MacOS 13'
      run: brew install lapack bzip2
      
    - if: matrix.os.name == 'MacOS 14 (M1)'
      run: brew install lapack bzip2
        
    - if: matrix.os.name == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-binutils mingw-w64-x86_64-gcc mingw-w64-x86_64-headers-git mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-lapack mingw-w64-x86_64-openblas mingw-w64-x86_64-libxml2 mingw-w64-x86_64-bzip2 mingw-w64-x86_64-python mingw-w64-x86_64-python-zstandard mingw-w64-x86_64-python-cffi make bison flex mingw-w64-x86_64-ca-certificates mingw-w64-x86_64-diffutils
    
    - name: Build ${{ matrix.projects.name }} project 
      run: |
        make data-cleanup && make ${{ matrix.projects.project }}
        if [[ "${{ matrix.os.name }}" == "Ubuntu 22" || "${{ matrix.os.name }}" == "Ubuntu 24" ]]; then
          make PHYSICELL_CPP=${{ matrix.os.compiler }} PROGRAM_NAME=${{ matrix.projects.binary }} static STATIC_OPENMP=/usr/lib/gcc/x86_64-linux-gnu/12/libgomp.a STATIC_LAPACK="/usr/lib/x86_64-linux-gnu/liblapack.a /usr/lib/x86_64-linux-gnu/libopenblas.a -static-libgfortran"
        else
          make PHYSICELL_CPP=${{ matrix.os.compiler }} PROGRAM_NAME=${{ matrix.projects.binary }} static
        fi
                
    - name: Inspect binary
      if: matrix.os.name == 'Ubuntu'
      run: |
        ldd ${{ matrix.projects.binary }}
    
    - name: Inspect mACOS binary
      if: matrix.os.name == 'MacOS 13' || matrix.os.name == 'MacOS 14 (M1)'
      run: |
        otool -L ${{ matrix.projects.binary }}
        otool -l ${{ matrix.projects.binary }}
        lipo -archs ${{ matrix.projects.binary }}
    
    - name: Inspect Windows binary
      if: matrix.os.name == 'Windows'
      run: |
        file ${{ matrix.projects.binary }}
        objdump -f ${{ matrix.projects.binary }}
        
    - name: Run ${{ matrix.projects.name }} project
      run: |
        python beta/test_run_sample.py ${{ matrix.projects.binary }} ${{ matrix.projects.config }} ${{ matrix.projects.max_time }}
    
    - name: Check ${{ matrix.projects.name }} project simulation results
      if: matrix.projects.output_folder != ''
      run: |
        python beta/test_diff_svg.py ${{ matrix.projects.output_folder }} tests/cases/output_${{ matrix.projects.project }}
